version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "config"
      include: "scope"
    labels: ["dependencies", "dependabot"]
    reviewers:
      - lgwk42
    assignees:
      - lgwk42      

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deploy"
      include: "scope"
    labels: [ "dependencies", "dependabot" ]
    reviewers:
      - lgwk42
    assignees:
      - lgwk42